version: '3.8'

services:
  app:
    image: php:8.2-fpm
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - laravel
    depends_on:
      - mongo
    environment:
      - PHP_EXTENSIONS=mongodb

  web:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - laravel
    depends_on:
      - app

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - laravel
    volumes:
      - ./data/db:/data/db

networks:
  laravel:
    driver: bridge
